services:
  auth-proxy:
    build: .
    ports:
      - 18000:18000
    volumes:
      - "./web:/app/web"
    environment:
      - HOST=0.0.0.0
      - PORT=18000
      - TARGET_URL=http://whoami:8000
      - AUTH_ACCESS_KEY=whoami
      - AUTH_EXPIRATION=24h

  whoami:
    image: traefik/whoami
    command:
      - --port=8000
    ports:
      - "8000:8000"
    restart: unless-stopped
