version: '3'

services:
  proxy:
    build: .
    ports:
      - 18000:18000
    volumes:
      - "./web:/app/web"
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=18000
      - TARGET_URL=http://whoami:8000
      - ACCESS_KEY=whoami

  whoami:
    image: traefik/whoami
    command:
      - --port=8000
    ports:
      - "8000:8000"
